### ISSUE TITLE
開発のフローを確定させたい

### ISSUE THREAD

**Issue by varietyshopletgo** [varietyshopletgo/decidim.reiwacity#11]
github flowを理解し、図解して共有したい
https://www.atmarkit.co.jp/ait/articles/1708/01/news015.html

**Comment by varietyshopletgo** [comment]
下記URLを参考にGitHub 統合-GitHub 統合の有効化を行う
https://devcenter.heroku.com/ja/articles/github-integration

**Comment by varietyshopletgo** [comment]
手動デプロイに成功
ホームページの正常な稼働を確認

**Comment by reiwacity** [comment]
local→remote→github→（手動で）herokuのフローで一旦おちついた
