### ISSUE TITLE
local開発環境を整えたい

### ISSUE THREAD

**Issue by varietyshopletgo** [varietyshopletgo/decidim.reiwacity#13]
エラーが出て動かない

**Comment by otspace0715** [comment]
どんなエラーだろ？

**Comment by varietyshopletgo** [comment]
https://devcenter.heroku.com/ja/articles/getting-started-with-rails5
以下、上記URLを参考に作業しました。

### Procfileに下記を追加
web: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}

### .envファイルに追記

### .env​ を ​.gitignore​ に追加

[OKAY] Loaded ENV .env File as KEY=VALUE Format
と表示が変わった

PG::ConnectionBad
fe_sendauth: no password supplied

エラーがまだ出ています。

**Comment by varietyshopletgo** [comment]
rails sでlocathost:3000にてWebページが表示されました。
しかし、本番環境で入力したデータは拾ってきていません。

→データベース詳しい友達に聞いたら、それは当たり前だと言われました。
ローカル開発で本番環境のデータふっとばしたら大変だから、違うデータベースを使うのが通常とのこと。

### やったこと
①初期設定時に下記URLを参照して、config/application.ymlに
DATABASE_HOST、DATABASE_USERNAMEDATABASE_PASSWORDを記述した
https://docs.decidim.org/en/install/manual/

②しかしheokuにデプロイする際に、heroku側の設定を上書きしてしまうのではと考え、
上記３つの項目について＃でコメントアウトした

③コメントアウトを外し、設定を有効化したところ、ローカルにてwebページが動作した。

ローカル開発環境用にPostgreSQLのインストールとデータベースの構成は必要ということがわかった。

**Comment by varietyshopletgo** [comment]
現在の設定だと`rails s`で動く。
`heroku local web`で表示したときと変わらない。

**Comment by varietyshopletgo** [comment]
共同開発者はmaster.keyを共有する必要があるため外部サービスにて共有
参考：チーム開発でのデプロイで注意すべき３つのポイント
https://techtechmedia.com/team-development-deploy/
